# Generated by Django 2.2.2 on 2019-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='img/noproduct.png', upload_to='images/'),
        ),
    ]
