# Generated by Django 2.2.2 on 2019-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='actualPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='offerPrice',
            field=models.IntegerField(default=0),
        ),
    ]
