# Generated by Django 2.2.2 on 2019-06-26 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190626_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actualPrice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='offerPrice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
