# Generated by Django 2.2.2 on 2019-06-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190626_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsofweek',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', unique=True),
        ),
    ]
