# Generated by Django 2.2.2 on 2019-06-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190626_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsofweek',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
